version: '3'

tasks:
  go:build:
    desc: Build the manager binary
    cmds:
      - go build -o bin/manager cmd/main.go

  go:test:
    desc: Run unit tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./pkg/... ./internal/config/...
      - go tool cover -func=coverage.out

  go:test:controller:
    desc: Run controller tests individually to avoid metrics conflicts
    cmds:
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_executeTemplate
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_validateTemplate
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_shouldProcess
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_validateGeneratorConfig
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_generateTemplateData
      - go test -v ./internal/controller/... -run TestGetMapKeys
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_handleDeletion
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_createOrUpdateSecret
      - go test -v ./internal/controller/... -run TestSecretSantaReconciler_updateStatus

  go:test:all:
    desc: Run all tests including controller tests individually
    cmds:
      - task: go:test
      - task: go:test:controller

  go:fmt:
    desc: Format and vet Go code
    cmds:
      - go fmt ./...
      - go vet ./...

  go:manifests:
    desc: Generate CRD manifests
    cmds:
      - export PATH=$PATH:$(go env GOPATH)/bin && controller-gen crd rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases

  docker:build:
    desc: Build Docker image
    cmds:
      - docker build -t secret-santa:latest .

  docker:push:
    desc: Build and push Docker image
    cmds:
      - docker build -t logiciq/secret-santa:latest .
      - docker push logiciq/secret-santa:latest

  e2e:run:
    desc: Run complete e2e test suite
    cmds:
      # Setup
      - go install sigs.k8s.io/kind@latest || echo "Failed to install kind"
      - go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest || echo "Failed to install controller-gen"
      - kind create cluster --config=e2e/k8s/kind-config.yaml --name=secret-santa-e2e || echo "Failed to create cluster"
      - kubectl config use-context kind-secret-santa-e2e
      
      # Generate CRDs
      - task: go:manifests
      
      # Deploy
      - kubectl delete deployment secret-santa-controller -n secret-santa-system --ignore-not-found=true
      - task: docker:build
      - kind load docker-image secret-santa:latest --name=secret-santa-e2e
      - kubectl create namespace secret-santa-system --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -f config/crd/bases/
      - kubectl apply -f config/rbac/
      - kubectl apply -f config/manager/
      - kubectl wait --for=condition=available --timeout=180s deployment/secret-santa-controller -n secret-santa-system
      
      # Test
      - cd e2e/k8s && go mod tidy && go test -v ./... -tags=e2e

  e2e:cleanup:
    desc: Cleanup e2e environment
    cmds:
      - kind delete cluster --name=secret-santa-e2e || echo "Failed to delete cluster"