apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: tls-example
  namespace: default
spec:
  template: |
    tls.crt: {{ .TLSCert.certificate }}
    tls.key: {{ .TLSKey.private_key_pem }}
  generators:
    - name: TLSKey
      type: tls_private_key
      config:
        algorithm: "RSA"
        rsa_bits: 2048
    - name: TLSCert
      type: tls_self_signed_cert
      config:
        key_pem: "{{ .TLSKey.private_key_pem }}"
        common_name: "example.com"
        # Optional fields with defaults:
        # validity_days: 365
        # dns_names: ["example.com"]
  secretType: "kubernetes.io/tls"
  labels:
    app: my-app
---
apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: password-example
  namespace: default
spec:
  template: |
    password: {{ .Password.password }}
    uuid: {{ .UUID.value }}
  generators:
    - name: Password
      type: random_password
      config:
        length: 32
    - name: UUID
      type: random_uuid
      config: {}
  secretType: "Opaque"