apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: tls-private-key-example
  namespace: default
spec:
  template: |
    private_key_pem: {{ .PrivateKey.private_key_pem | b64enc }}
    public_key_pem: {{ .PrivateKey.public_key_pem | b64enc }}
    public_key_openssh: {{ .PrivateKey.public_key_openssh | b64enc }}
  generators:
    - name: PrivateKey
      type: tls_private_key
      config:
        algorithm: RSA
        rsa_bits: 4096
  secretType: "Opaque"
---
apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: tls-self-signed-example
  namespace: default
spec:
  template: |
    tls.crt: {{ .SelfSignedCert.cert_pem | b64enc }}
    tls.key: {{ .PrivateKey.private_key_pem | b64enc }}
  generators:
    - name: PrivateKey
      type: tls_private_key
      config:
        algorithm: RSA
        rsa_bits: 4096
    - name: SelfSignedCert
      type: tls_self_signed_cert
      config:
        common_name: "example.com"
        private_key_pem: "{{ .PrivateKey.private_key_pem }}"
        validity_period_hours: 8760
  secretType: "kubernetes.io/tls"
---
apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: tls-csr-example
  namespace: default
spec:
  template: |
    csr.pem: {{ .CSR.cert_request_pem | b64enc }}
    private_key.pem: {{ .PrivateKey.private_key_pem | b64enc }}
  generators:
    - name: PrivateKey
      type: tls_private_key
      config:
        algorithm: RSA
        rsa_bits: 4096
    - name: CSR
      type: tls_cert_request
      config:
        private_key_pem: "{{ .PrivateKey.private_key_pem }}"
        common_name: "example.com"
        dns_names: ["example.com", "www.example.com"]
  secretType: "Opaque"