apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: tls-example
  namespace: default
spec:
  template: |
    tls.crt: {{ .TLSCert.cert_pem | b64enc }}
    tls.key: {{ .TLSCert.private_key_pem | b64enc }}
  generators:
    - name: TLSCert
      type: tls_self_signed_cert
      config:
        common_name: "example.com"
  secretType: "kubernetes.io/tls"
  labels:
    app: my-app
---
apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: password-example
  namespace: default
spec:
  template: |
    password: {{ .Password.password }}
    uuid: {{ .UUID.value }}
  generators:
    - name: Password
      type: password
      config:
        length: 32
    - name: UUID
      type: uuid
  secretType: "Opaque"