apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: tls-example
  namespace: default
spec:
  template: |
    tls.crt: {{ .TLSCert.cert_pem | default "" | b64enc }}
    tls.key: {{ .TLSCert.private_key_pem | default "" | b64enc }}
  generators:
    - name: TLSCert
      type: tls_self_signed_cert
      config:
        common_name: "example.com"
        # Optional: validity_days, key_size, dns_names
  secretType: "kubernetes.io/tls"
  labels:
    app: my-app
---
apiVersion: secrets.secret-santa.io/v1alpha1
kind: SecretSanta
metadata:
  name: password-example
  namespace: default
spec:
  template: |
    password: {{ .Password.password | default "" }}
    uuid: {{ .UUID.value | default "" }}
  generators:
    - name: Password
      type: random_password
      config:
        length: 32
    - name: UUID
      type: uuid
      config: {}
  secretType: "Opaque"